name: golangci-lint
on:
  pull_request:
    branches:
      - main
  push:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: golangci-lint
        uses: golangci/golangci-lint-action@main
        with:
          version: v1.38
